### ISSUE TITLE
what does footer refer to in line 130 of style.css?

### ISSUE THREAD

**Issue by prawla** [prawla/CDGD304-01#12]
I don't see the class in the html

**Comment by saulbaizman** [comment]
Which HTML file are you referring to?

**Comment by prawla** [comment]
Design/about.html

**Comment by saulbaizman** [comment]
Look at line 159 in style.css. You'll see that we've defined the HTML element `section.navigation` as a grid area with the name `footer`. Does that make sense?

**Comment by prawla** [comment]
yes! thank you

**Comment by saulbaizman** [comment]
Hooray! I'm closing this issue.
