### ISSUE TITLE
How do I have two seperate vertical colours in the background?

### ISSUE THREAD

**Issue by prawla** [prawla/CDGD304-01#3]

**Comment by prawla** [comment]
![img_4495](https://user-images.githubusercontent.com/31822848/46180057-2bbfcc00-c28c-11e8-93a0-a1043d812b27.JPG)

**Comment by saulbaizman** [comment]
Assuming the photo ought to be rotated 90 degrees clockwise, you could create two divs with a width of 50% and float the left div. But this has to do with layout, a very large subject. If you really want to go there, check out [learnlayout.com](https://learnlayout.com) for an old-school layout tutorial and [gridbyexample.com](https://gridbyexample.com) for a new-school layout tutorial.

**Comment by prawla** [comment]
Thank you!

**Comment by prawla** [comment]
![img_4496](https://user-images.githubusercontent.com/31822848/46222405-2b701100-c31e-11e8-9468-da717f659b97.JPG)
